Первое задание
prtngn/testGuru pull request #1
Opened 2021-09-07 08:22 UTC by prtngn

2021-09-07 17:28 UTC, BubuntuClu requested changes

2021-09-07 17:28 UTC, BubuntuClu commented on config/initializers/version.rb
> +    VERSION = "0.0.1"
0.1.0

2021-09-07 17:28 UTC, BubuntuClu commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
в данном задании не надо использовать контроллер и вьюхи.

кстати, если ты их исользуешь, то у тебя должен быть настроен роутинг

надо страницы сделать статичными в папке `public`

2021-09-07 17:28 UTC, BubuntuClu commented on app/views/about/about.html.erb
> +<p>Обучение проходит в онлайн школе <%= link_to('Thinknetica', 'https://www.thinknetica.com') %></p>
ссылки на сторонние ресурсы открываем в новой вкладке

2021-09-07 17:28 UTC, BubuntuClu commented on app/views/about/author.html.erb
> +    <td><%= link_to('Link', 'https://github.com/prtngn') %></td>
ссылки на сторонние ресурсы открываем в новой вкладке

2021-09-07 18:44 UTC, prtngn commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
роут то есть, только он случайно в initial commit попал

2021-09-08 07:03 UTC, BubuntuClu commented on public/about.html
> +    <p>Обучение проходит в онлайн школе <a href="https://www.thinknetica.com" target="_blank">Thinknetica</a></p>
>Добавьте статическую страницу /about/author с информацией об авторе (включая ссылку на GitHub профиль)

эту страницу потерял

2021-09-09 19:21 UTC, merged