Add associations
prtngn/testGuru pull request #5
Opened 2021-09-19 09:19 UTC by prtngn

2021-09-19 18:26 UTC, BubuntuClu requested changes

2021-09-19 18:26 UTC, BubuntuClu commented on app/models/test.rb
> +  has_one :author, through: :test_author, source: :user
зачем тут сделано получение через другую ассоциацию?

2021-09-19 18:26 UTC, BubuntuClu commented on app/models/user.rb
нужно добавить ассоциацию на получение всех созданных тестов пользователем

2021-09-19 18:26 UTC, BubuntuClu commented on app/models/user.rb
>      Test.joins('JOIN test_users ON test_users.test_id = tests.id')
отрефактори этот запрос с использованием новой ассоциации `tests`, которую ты только что добавил

2021-09-19 18:26 UTC, BubuntuClu commented on app/models/test.rb
> +  has_one :author, through: :test_author, source: :user
и за счет какого столбца будет работать эта ассоциация?

2021-09-20 04:41 UTC, prtngn commented on app/models/test.rb
> +  has_one :author, through: :test_author, source: :user
@BubuntuClu а каким образом сделать еще одну взять с таблицей User без связующей таблицы?

2021-09-20 07:05 UTC, BubuntuClu requested changes

2021-09-20 07:05 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :test_authors
по курсу подразумевается что у теста может быть только один автор. такая ассоциация не потрубется.

2021-09-20 07:05 UTC, BubuntuClu commented on app/models/test.rb
> +  has_one :author, through: :test_author, source: :user
так же как и все остальыне связь у тебя сделаны, где используется принцип "принадлежности". тесты "принадлежат" пользователю. то есть он автор этих тестов.

как у тебя реализована связь принадлежности тестов к категории?

2021-09-20 07:05 UTC, BubuntuClu commented on db/migrate/20210919091251_create_test_authors.rb
> +    create_table :test_authors do |t|
эта таблица не нужна

2021-09-24 07:12 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
чем отличается `users` от `user`? не понятен смысл ассоциации в таких именах, надо тут задат кастомное имя, что-то типа `creator`

2021-09-25 14:19 UTC, merged